#!/bin/bash

docker run  -it --rm --name minidlna --net=host -v /srv/minidlan/database/:/database -v /srv/smbshares/music:/media -e MINIDLNA_MEDIA_DIR=/media  -e MINIDLNA_PORT=8200 -e MINIDLNA_FRIENDLY_NAME=dockerhost -e MINIDLNA_LOG_DIR=/media -e MINIDLNA_LOG_LEVEL=debug minidlna
